{
  "hash": "fce09b078322d206dea8e2dec16f0d7a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Diffusion Modelling\"\nauthor: \"Clare McGarvey, Paloma Navarro and Anita Di Gennaro\"\n---\n\n\n\n\n\n## Introduction\n\nThis analytical section focuses on the spread of information through the Epstein network using a Susceptible-Infected-Recovered (SIR) framework. We derive the network's theoretical epidemic threshold, simulate spread above and below it, and test the effect of targeted interventions. These interventions examine targeting seeds or suppressing spreaders by centrality, rather than at random, and found that how far and how fast information spreads through the network can be highly influenced. \n\nThis file uses the same network constructed in Link Prediction, drawing from the top 1,700 nodes and examining the giant component. As before, entities with \"unknown\" composite nodes are removed as their inflated connectivity would distort results. \n\n## Data Preparation\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsource(\"data-prep.R\")\nlibrary(purrr)\nlibrary(tibble)\n```\n:::\n\n\n\n\n\n## Network Construction\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nedgelist <- raw[, c(\"actor\", \"target\")]\n\nentity_freq <- table(c(edgelist$actor, edgelist$target))\ntop1700       <- names(sort(entity_freq, decreasing = TRUE))[1:1700]\n\nedgelist <- edgelist[edgelist$actor %in% top1700 & edgelist$target %in% top1700, ]\n\n# Build and simplify \nepstein <- graph.data.frame(edgelist, directed = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: `graph.data.frame()` was deprecated in igraph 2.0.0.\nℹ Please use `graph_from_data_frame()` instead.\n```\n\n\n:::\n\n```{.r .cell-code}\nepstein <- igraph::simplify(epstein)\nepstein\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIGRAPH 4bb1eb4 UN-- 1639 6280 -- \n+ attr: name (v/c)\n+ edges from 4bb1eb4 (vertex names):\n [1] Jeffrey Epstein--Palm Beach Police Department\n [2] Jeffrey Epstein--Larry Visoski               \n [3] Jeffrey Epstein--Prince Andrew               \n [4] Jeffrey Epstein--Michael Reiter              \n [5] Jeffrey Epstein--grand jury                  \n [6] Jeffrey Epstein--Guy Fronstin                \n [7] Jeffrey Epstein--Alex Acosta                 \n [8] Jeffrey Epstein--Ric Bradshaw                \n+ ... omitted several edges\n```\n\n\n:::\n\n```{.r .cell-code}\n# Filter out \"unknown\" composite nodes \nunknown_nodes <- V(epstein)$name[grepl(\"unknown\", V(epstein)$name, ignore.case = TRUE)]\ncat(\"Removing\", length(unknown_nodes), \"unknown composite nodes\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRemoving 107 unknown composite nodes\n```\n\n\n:::\n\n```{.r .cell-code}\nepstein <- delete_vertices(epstein, unknown_nodes)\n\n# Take the giant component\nepstein <- decompose(epstein)[[which.max(sapply(decompose(epstein), vcount))]]\n\n# Node and Edges Count\ncat(\"Nodes:\", vcount(epstein), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNodes: 1491 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Edges:\", ecount(epstein), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEdges: 5124 \n```\n\n\n:::\n:::\n\n\n\n\n## The SIR Model\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 0 = Susceptible, 1 = Infected, 2 = Recovered\nsim_sir <- function(g, beta, mu, seeds){\n  state <- rep(0, vcount(g))\n  state[seeds] <- 1\n  t <- 0\n  table <- data.frame(t = 0, inf = seeds)\n  while(sum(state == 1) > 0){\n    t <- t + 1\n    infected <- which(state == 1)\n    state[infected] <- ifelse(runif(length(infected)) < mu, 2, 1)\n\n    infected    <- which(state == 1)\n    susceptible <- which(state == 0)\n    contacts <- as.numeric(unlist(adjacent_vertices(g, infected)))\n    contacts <- contacts[contacts %in% susceptible]\n    new_infected <- unique(contacts[runif(length(contacts)) < beta])\n    if(length(new_infected) > 0){\n      state[new_infected] <- 1\n      table <- rbind(table, data.frame(t, inf = new_infected))\n    }\n  }\n  table\n}\n```\n:::\n\n\n\n\n\n## Simulation Helpers\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN_RUNS <- 50\n\nsim_sir_novax <- function(g, beta, mu, seeds, no_spread = c()) {\n  state <- rep(0, vcount(g))\n  state[seeds] <- 1\n  t <- 0\n  table <- data.frame(t = 0, inf = seeds)\n  while (sum(state == 1) > 0) {\n    t <- t + 1\n    infected <- which(state == 1)\n    state[infected] <- ifelse(runif(length(infected)) < mu, 2, 1)\n\n    infected    <- which(state == 1)\n    spreaders   <- infected[!infected %in% no_spread]\n    susceptible <- which(state == 0)\n    contacts <- as.numeric(unlist(adjacent_vertices(g, spreaders)))\n    contacts <- contacts[contacts %in% susceptible]\n    new_infected <- unique(contacts[runif(length(contacts)) < beta])\n    if (length(new_infected) > 0) {\n      state[new_infected] <- 1\n      table <- rbind(table, data.frame(t, inf = new_infected))\n    }\n  }\n  table\n}\n\navg_sim <- function(g, beta, mu, n_seeds, n_runs = N_RUNS, no_spread = c()) {\n  map_dfr(seq_len(n_runs), function(i) {\n    seeds <- sample(seq_len(vcount(g)), n_seeds)\n    sim_sir_novax(g, beta, mu, seeds, no_spread) |>\n      group_by(t) |>\n      summarise(ninf = n(), .groups = \"drop\") |>\n      mutate(run = i)\n  })\n}\n\nper_run_stats <- function(runs_df) {\n  runs_df |>\n    group_by(run) |>\n    summarise(total = sum(ninf), peak_t = t[which.max(ninf)], .groups = \"drop\")\n}\n\navg_total <- function(s) round(mean(s$total))\navg_peak  <- function(s) round(mean(s$peak_t))\n```\n:::\n\n\n\n\n\n## Epidemic Threshold\n\nFind the theoretical epidemic threshold for βc your network for the information to reach a significant number of nodes.\n\nFirstly, the theoretical epidemic threshold (βc) of the Epstein network is found. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Theoretical epidemic threshold\nmu    <- 0.1\nkavg  <- mean(degree(epstein))\nksq   <- mean(degree(epstein)^2)\nbetac <- mu * kavg / (ksq - kavg)\n\ncat(\"<k>:   \", kavg, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<k>:    6.873239 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"<k^2>: \", ksq, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<k^2>:  470.495 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"kappa: \", ksq/kavg, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nkappa:  68.45316 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"mu:    \", mu, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmu:     0.1 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"beta_c:\", betac, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbeta_c: 0.00148251 \n```\n\n\n:::\n:::\n\n\n\n\n\nThe average degree of the network is 6.87, suggesting that a node (person) in the Epstein files is directly connected to roughly seven others, and that information does not spread as fast as might be expected.\n\nThe branching factor is a significantly higher number (68.4), as Epstein himself, Donald Trump, Alan Dershowitz, and a handful of other important actors in the network are vastly more connected than the average node (refer to Network Exploration). Therefore, any random person who received information is far more likely to have received it from one of those main hubs, rather than from a peripheral contact.\n\nβc represents the probability that an infected person infects a specific neighbor in one step, and in this context the threshold returns as a very small number. The branching factor's value resonates with this low transmission probability of approximately 0.14%: the network is hub-dominated, meaning certain elements have a much stronger infecting power than others.\n\n## Simulating Spread Above and Below Threshold\n\nUsing a randomly selected 1% of initial spreaders, we simulate the SIR model for a range below and above the theoretical threshold βc found above and plot total infections as a function of β.  \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2406)\n\n# One realization at β = 0.015\nseeds <- sample(1:vcount(epstein), vcount(epstein) * 0.01)\nrealization <- sim_sir(epstein, beta = 0.015, mu = 0.1, seeds = seeds)\n\n# Infection curve over time\nrealization |> group_by(t) |> summarise(ninf = n()) |>\n  ggplot(aes(x = t, y = ninf)) + geom_line() +\n  labs(x = \"Time step\", y = \"New infections\",\n       title = \"SIR infection curve at \\u03b2 = 0.015\")\n```\n\n::: {.cell-output-display}\n![](03-diffusion-modelling_files/figure-html/simulation-range-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Results + visualization\nresults <- map_dfr(seq(0, 0.03, 0.001),   # beta range adapted to our β\n        \\(beta){\n          seeds       <- sample(1:vcount(epstein), vcount(epstein) * 0.01)\n          realization <- sim_sir(epstein, beta, mu, seeds)\n          data.frame(beta, ninf = nrow(realization))\n        })\n\nresults |> ggplot(aes(x = beta, y = ninf)) + \n  geom_point() +\n  geom_vline(xintercept = betac, linetype = 2) +\n  labs(x = expression(beta), y = \"Total infected\",\n       title = \"Final outbreak size vs. \\u03b2 (random 1% seeds, \\u03bc = 0.1)\")\n```\n\n::: {.cell-output-display}\n![](03-diffusion-modelling_files/figure-html/simulation-range-2.png){width=672}\n:::\n:::\n\n\n\n\n\nThe first plot shows a single realization where β = 0.015 (approximately 10 times above the theoretical threshold). The infection curve shows an initial peak, followed by a series of about 25 time steps, during which there are minimal new infections. After this initial delay, the information starts to spread again, with new staggered infections. This suggests that the infection really only begins once one of the main actors (e.g. Epstein or Maxwell) are reached, propagating the 'news'. This is in line with the behavior of hub-dominated networks, such as the Epstein files. Over time, the infection curve starts to die out, as the main hubs are informed.\n\nBy displaying the total number of infected nodes as a function of β, with βc signaled through the vertical dotted line, it can be noticed that for β above βc (the threshold) the infection starts to steeply spread. It eventually grows to reach 600-800 infected nodes. Overall, the main conclusion from this visualization is that the point where information goes from *dying out* to *spreading across the network* corresponds to the theoretical threshold previously calculated.\n\n## Targeted vs. Random Seeding\n\nTo compare targeted and random seeding, a β of approximately 30 times the threshold (0.05) was selected to ensure the outbreak takes off in every run and the observed difference can be attributed to the seeding strategy. Firstly, the centrality measure that best predicts early infection is identified, through a comparison of infection times between degree, closeness, betweenness, and page rank. Secondly, the best measure is then taken and the top 1% of nodes are selected as the targeted seed set. The difference between random selection and the targeted selection is examined through both the total number of infections and the difference in the infection peak. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2406)\nbeta <- 0.05\n\n# One SIR realization with 1% random seeds to get time of infection per node\nseeds <- sample(1:vcount(epstein), vcount(epstein) * 0.01)\nrealization <- sim_sir(epstein, beta = beta, mu = mu, seeds = seeds)\n\n# Merge centralities with infection times\ntable_d  <- data.frame(inf = seq_len(vcount(epstein)), degree = as.numeric(degree(epstein))) |> merge(realization)\ntable_c  <- data.frame(inf = seq_len(vcount(epstein)), closeness = as.numeric(closeness(epstein))) |> merge(realization)\ntable_pr <- data.frame(inf = seq_len(vcount(epstein)), page_rank = as.numeric(page_rank(epstein)$vector)) |> merge(realization)\ntable_b  <- data.frame(inf = seq_len(vcount(epstein)), betweenness = as.numeric(betweenness(epstein))) |> merge(realization)\n\ntable3 <- table_d |> merge(table_c) |> merge(table_pr) |> merge(table_b)\ncor(table3$t, table3[, -c(1, 2)])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         degree  closeness  page_rank betweenness\n[1,] -0.1290938 -0.2875016 -0.1107542 -0.06135933\n```\n\n\n:::\n:::\n\n\n\n\n\nAll the centrality measures are negative, which is reasonable, since the network is hub-centered and the more central a node is, the earlier it is expected to be infected. Here, the stronger metric is the *closeness*.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2406)\nn_seeds <- round(vcount(epstein) * 0.01)\n\n# Centrality-based seeds (1%) using closeness\nseeds_centrality <- closeness(epstein) |>\n  enframe(name = \"inf\", value = \"closeness\") |>\n  slice_max(closeness, n = n_seeds)\n\n# Convert character node names to integer vertex IDs for sim_sir\nseeds_centrality_ids <- match(seeds_centrality$inf, V(epstein)$name)\n\n# Helper: average N_RUNS simulations from a FIXED seed set\navg_sim_fixed_seeds <- function(g, beta, mu, seeds, n_runs = N_RUNS) {\n  map_dfr(seq_len(n_runs), function(i) {\n    sim_sir(g, beta, mu, seeds) |>\n      group_by(t) |>\n      summarise(ninf = n(), .groups = \"drop\") |>\n      mutate(run = i)\n  })\n}\n\n# Random seeding\nruns_random_seed  <- avg_sim(epstein, beta, mu, n_seeds)\ncurve_random_seed <- runs_random_seed |> group_by(t) |> summarise(ninf = mean(ninf), .groups = \"drop\")\n\n# Targeted seeding\nruns_targeted_seed  <- avg_sim_fixed_seeds(epstein, beta, mu, seeds_centrality_ids)\ncurve_targeted_seed <- runs_targeted_seed |> group_by(t) |> summarise(ninf = mean(ninf), .groups = \"drop\")\n\nggplot() +\n  geom_line(data = curve_random_seed,   aes(x = t, y = ninf, col = \"Random\")) +\n  geom_line(data = curve_targeted_seed, aes(x = t, y = ninf, col = \"Targeted\")) +\n  labs(x = \"Time step\", y = \"Mean new infections\",\n       title = paste0(\"Infection curves: random vs. centrality-based seeds\\n(\\u03b2 = 0.05, mean over \", N_RUNS, \" runs)\"),\n       color = \"Seeding strategy\")\n```\n\n::: {.cell-output-display}\n![](03-diffusion-modelling_files/figure-html/targeted-seeding-simulation-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nstats_random_seed   <- per_run_stats(runs_random_seed)\nstats_targeted_seed <- per_run_stats(runs_targeted_seed)\n\ncat(\"Avg total infected (random):   \", avg_total(stats_random_seed),   \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAvg total infected (random):    983 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Avg total infected (targeted): \", avg_total(stats_targeted_seed), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAvg total infected (targeted):  967 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Difference:\", avg_total(stats_targeted_seed) - avg_total(stats_random_seed), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDifference: -16 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Avg peak time (random):   \", avg_peak(stats_random_seed),   \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAvg peak time (random):    7 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Avg peak time (targeted): \", avg_peak(stats_targeted_seed), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAvg peak time (targeted):  3 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Difference:\", avg_peak(stats_targeted_seed) - avg_peak(stats_random_seed), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDifference: -4 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SD (random):    \",sd(stats_random_seed$total), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSD (random):     73.80898 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SD (targeted):  \",sd(stats_targeted_seed$total), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSD (targeted):   79.7555 \n```\n\n\n:::\n:::\n\n\n\n\n\nAveraged over 50 runs, the total infected nodes is almost indistinguishable between targeted and random seeding (967 vs. 983) as the 16 node gap is small relative to the run-to-run variability of the simulation (SD ≈ 74–80 nodes per scenario). At this large β (0.05, roughly 30 times βc), the seeding strategy has no detectable effect on the total infections and the infection spreads easily enough that both strategies reach around two-thirds of the network, so the difference between targeted and randomized infected is not as striking as expected.\n\nIn contrast, the peak time of infection is now reached earlier in the targeted case compared to the randomized one, peaking four time steps sooner (t = 3 vs t = 7). This behavior can also be seen in the graph, where the targeted curve rises and peaks before the random one.\n\nUltimately, choosing seeds by the strongest centrality measure for the network, here closeness, shows that whilst targeted infection has a negligible effect on total infections, it peaks four time steps earlier than the random one, indicating that the information spreads faster. Centrality thus matters more for speed of transmission, rather than scale, when the network is well above its epidemic threshold. \n\n## A Quarantine Strategy\n\nUsing the same β, a \"quarantine strategy\" will be designed, where 20% of the susceptible population are quarantined during the exponential growth phase. These quarantined nodes are then released 8 time steps later, where they are newly susceptible. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2406)\nbeta_val <- 0.1\nmu_val   <- 0.1\n\npilot_seeds <- sample(seq_len(vcount(epstein)), round(vcount(epstein) * 0.01))\npilot       <- sim_sir(epstein, beta = beta_val, mu = mu_val, pilot_seeds) |>\n  group_by(t) |> summarise(ninf = n(), .groups = \"drop\")\n\nggplot(pilot, aes(x = t, y = ninf)) +\n  geom_line() + geom_point() +\n  scale_y_log10() +\n  labs(x = \"Time step\", y = \"New infections (log scale)\",\n       title = \"Pilot SIR run: identifying exponential growth phase\",\n       subtitle = \"Straight line on log scale = exponential growth\")\n```\n\n::: {.cell-output-display}\n![](03-diffusion-modelling_files/figure-html/finding-exponential-growth-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Growth rate between consecutive time steps\npilot <- pilot |>\n  mutate(growth_rate = ninf / lag(ninf))\n\nprint(pilot)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 39 × 3\n       t  ninf growth_rate\n   <dbl> <int>       <dbl>\n 1     0    15      NA    \n 2     1     7       0.467\n 3     2    42       6    \n 4     3    63       1.5  \n 5     4    87       1.38 \n 6     5   109       1.25 \n 7     6   139       1.28 \n 8     7   110       0.791\n 9     8    79       0.718\n10     9    79       1    \n# ℹ 29 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\n# Determine quarantine timing from pilot\nt_start <- pilot$t[which.max(pilot$growth_rate[-1]) + 1]\nt_end   <- t_start + 8\ncat(\"Quarantine begins at t =\", t_start, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nQuarantine begins at t = 2 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Quarantine ends   at t =\", t_end,   \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nQuarantine ends   at t = 10 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# SIM-SIR model \nsim_sir_quarantine <- function(g, beta, mu, seeds, t_quarantine, quarantine_duration = 8, quarantine_frac = 0.20){\n  state <- rep(0, vcount(g)) # 0: Susceptible, 1: Infected, 2: Recovered, 3: Quarantined\n  state[seeds] <- 1\n  t <- 0\n  table <- data.frame(t=0, inf=seeds)\n  quarantined_nodes <- c()\n  \n  while(sum(state==1) > 0){\n    t <- t + 1\n    \n    if(t == t_quarantine){\n      susceptible <- which(state == 0)\n      n_quarantine <- floor(length(susceptible) * quarantine_frac)\n      if(n_quarantine > 0){\n        quarantined_nodes <- sample(susceptible, n_quarantine)\n        state[quarantined_nodes] <- 3\n      }\n    }\n    \n    ## I -> R\n    infected <- which(state==1)\n    state[infected] <- ifelse(runif(length(infected)) < mu, 2, 1)\n\n    ## S -> I\n    infected     <- which(state==1)\n    susceptible  <- which(state==0)\n    contacts     <- as.numeric(unlist(adjacent_vertices(g, infected)))\n    contacts     <- contacts[contacts %in% susceptible]\n    new_infected <- unique(contacts[runif(length(contacts)) < beta])\n\n    if(length(new_infected) > 0){\n     state[new_infected] <- 1\n     table <- rbind(table, data.frame(t, inf=new_infected))\n    }\n\n    # Release quarantine after infection step so released nodes\n    # can only be infected from t+1 onwards\n    if(t == (t_quarantine + quarantine_duration)){\n     state[quarantined_nodes] <- 0\n    }\n  }\n  table\n}\n\navg_sim_quarantine <- function(g, beta, mu, n_seeds, n_runs = N_RUNS,\n                                t_quarantine, quarantine_duration = 8, quarantine_frac = 0.20) {\n  map_dfr(seq_len(n_runs), function(i) {\n    seeds <- sample(seq_len(vcount(g)), n_seeds)\n    sim_sir_quarantine(g, beta, mu, seeds, t_quarantine, quarantine_duration, quarantine_frac) |>\n      group_by(t) |> summarise(ninf = n(), .groups = \"drop\") |> mutate(run = i)\n  })\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2406)\nn_seeds_q4 <- round(vcount(epstein) * 0.01)\n\nruns_normal     <- avg_sim(epstein, beta_val, mu_val, n_seeds_q4)\nruns_quarantine <- avg_sim_quarantine(epstein, beta_val, mu_val, n_seeds_q4, t_quarantine = t_start)\n\ncurve_normal     <- runs_normal     |> group_by(t) |> summarise(ninf = mean(ninf), .groups = \"drop\")\ncurve_quarantine <- runs_quarantine |> group_by(t) |> summarise(ninf = mean(ninf), .groups = \"drop\")\n\nggplot() +\n  geom_line(data = curve_normal,     aes(x = t, y = ninf, col = \"No Quarantine\")) +\n  geom_line(data = curve_quarantine, aes(x = t, y = ninf, col = \"Quarantine 20%\")) +\n  geom_vline(xintercept = t_start, linetype = \"dashed\", colour = \"grey40\") +\n  geom_vline(xintercept = t_end,   linetype = \"dashed\", colour = \"grey40\") +\n  annotate(\"text\", x = t_start + 0.2, y = Inf,\n           label = \"Quarantine\\nbegins\", vjust = 1.5, hjust = 0, size = 3, colour = \"grey40\") +\n  annotate(\"text\", x = t_end + 0.2, y = Inf,\n           label = \"Quarantine\\nends\", vjust = 1.5, hjust = 0, size = 3, colour = \"grey40\") +\n  labs(y = \"Mean new infections\", x = \"Time\",\n       title = paste0(\"Effect of Quarantine Strategy (mean over \", N_RUNS, \" runs)\"),\n       colour = \"Scenario\")\n```\n\n::: {.cell-output-display}\n![](03-diffusion-modelling_files/figure-html/quarantine-simulation-1.png){width=672}\n:::\n\n```{.r .cell-code}\nstats_q4_normal     <- per_run_stats(runs_normal)\nstats_q4_quarantine <- per_run_stats(runs_quarantine)\n\n# Metrics\ncat(\"── Average total infected ──────────────────────────\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n── Average total infected ──────────────────────────\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"No quarantine:  \", avg_total(stats_q4_normal), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNo quarantine:   1200 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Quarantine 20%: \", avg_total(stats_q4_quarantine), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nQuarantine 20%:  1175 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"── Difference vs. no-quarantine ────────────────────\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n── Difference vs. no-quarantine ────────────────────\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Quarantine 20%: \", avg_total(stats_q4_quarantine) - avg_total(stats_q4_normal),\n    sprintf(\"(%.1f%%)\\n\\n\", 100 * (avg_total(stats_q4_quarantine) - avg_total(stats_q4_normal)) / avg_total(stats_q4_normal)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nQuarantine 20%:  -25 (-2.1%)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"── Average peak time ───────────────────────────────\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n── Average peak time ───────────────────────────────\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"No quarantine:  \", mean(stats_q4_normal$peak_t),     \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNo quarantine:   5.06 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Quarantine 20%: \", mean(stats_q4_quarantine$peak_t), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nQuarantine 20%:  5.76 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"── Difference in peak time vs. no-quarantine ───────\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n── Difference in peak time vs. no-quarantine ───────\n```\n\n\n:::\n\n```{.r .cell-code}\ndiff_peak <- mean(stats_q4_quarantine$peak_t) - mean(stats_q4_normal$peak_t)\ncat(\"Quarantine 20%: \", round(diff_peak, 2),\n    sprintf(\"(%.1f%%)\\n\", 100 * diff_peak / mean(stats_q4_normal$peak_t)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nQuarantine 20%:  0.7 (13.8%)\n```\n\n\n:::\n:::\n\n\n\n\n\nOn average, introducing a quarantine of 20% of the population lowers the total infections by 2.1%. With no quarantine the initial peak results in the highest number of new infections and then trends downwards. When there's a quarantine, on average, a second peak is created once the quarantined group is let out. This peak is not as intense as the first and the infections trend downwards from there. Additionally, introducing a quarantine delayed the peak by t = 0.7. \n\n## Suppressing Spread\n\nWe now examine how the spread of information is effected when a set of actors are prevented from passing it on. Rather than removing nodes, we simulate 'silent' nodes who can receive the information but not share it. Two methods of silent node selection are compared: A) random selection, B) targeting actors with the highest closeness centrality. As each simulation is stochastic, we average results over 50 independent runs per scenario to find the trend for each and enable a stable comparison. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2406)\nn_seeds_full <- round(vcount(epstein) * 0.01)\nruns_normal_5  <- avg_sim(epstein, beta_val, mu_val, n_seeds_full)\ncurve_normal_5 <- runs_normal_5 |> group_by(t) |> summarise(ninf = mean(ninf), .groups = \"drop\")\n\n# Random 5% silenced — pass indices via no_spread instead of deleting them\nvax_random  <- sample(seq_len(vcount(epstein)), round(vcount(epstein) * 0.05))\nruns_random  <- avg_sim(epstein, beta_val, mu_val, n_seeds_full, no_spread = vax_random)\ncurve_random <- runs_random |> group_by(t) |> summarise(ninf = mean(ninf), .groups = \"drop\")\n\n# Targeted (closeness) 5% silenced\nvax_centrality_names <- closeness(epstein) |>\n  enframe(name = \"inf\", value = \"closeness\") |>\n  slice_max(closeness, n = round(vcount(epstein) * 0.05)) |>\n  pull(inf)\n\n# closeness() returns names; no_spread compares against numeric vertex indices\nvax_centrality <- match(vax_centrality_names, V(epstein)$name)\n\nruns_central  <- avg_sim(epstein, beta_val, mu_val, n_seeds_full, no_spread = vax_centrality)\ncurve_central <- runs_central |> group_by(t) |> summarise(ninf = mean(ninf), .groups = \"drop\")\n\nggplot() +\n  geom_line(data = curve_normal_5, aes(x = t, y = ninf, col = \"No Suppression\")) +\n  geom_line(data = curve_random,   aes(x = t, y = ninf, col = \"Random 5% Suppression\")) +\n  geom_line(data = curve_central,  aes(x = t, y = ninf, col = \"Targeted 5% Suppression\")) +\n  labs(y = \"Mean new infections\", x = \"Time\",\n       title = paste0(\"Random vs. Targeted Information Suppression\\n(mean over \", N_RUNS, \" runs)\"),\n       color = \"Scenario\")\n```\n\n::: {.cell-output-display}\n![](03-diffusion-modelling_files/figure-html/suppression-simulation-1.png){width=672}\n:::\n\n```{.r .cell-code}\nstats_normal_5 <- per_run_stats(runs_normal_5)\nstats_random   <- per_run_stats(runs_random)\nstats_central  <- per_run_stats(runs_central)\n\ncat(\"── Average total infected ──────────────────────────\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n── Average total infected ──────────────────────────\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"No suppression:            \", avg_total(stats_normal_5),  \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNo suppression:             1200 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Random 5% suppression:     \", avg_total(stats_random),  \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRandom 5% suppression:      1182 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Targeted 5% suppression:   \", avg_total(stats_central), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTargeted 5% suppression:    788 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"── Difference vs. no-suppression ───────────────────────\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n── Difference vs. no-suppression ───────────────────────\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Random suppression:        \", avg_total(stats_random)  - avg_total(stats_normal_5),\n    sprintf(\"(%.1f%%)\\n\", 100 * (avg_total(stats_random)  - avg_total(stats_normal_5)) / avg_total(stats_normal_5)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRandom suppression:         -18 (-1.5%)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Targeted suppression:      \", avg_total(stats_central) - avg_total(stats_normal_5),\n    sprintf(\"(%.1f%%)\\n\", 100 * (avg_total(stats_central) - avg_total(stats_normal_5)) / avg_total(stats_normal_5)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTargeted suppression:       -412 (-34.3%)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Targeted vs. random:   \", avg_total(stats_central) - avg_total(stats_random),\n    sprintf(\"(%.1f%%)\\n\\n\", 100 * (avg_total(stats_central) - avg_total(stats_random)) / avg_total(stats_random)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTargeted vs. random:    -394 (-33.3%)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"── Average peak time ───────────────────────────────\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n── Average peak time ───────────────────────────────\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"No suppression:            \", avg_peak(stats_normal_5),  \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNo suppression:             5 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Random 5% suppression:     \", avg_peak(stats_random),  \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRandom 5% suppression:      5 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Targeted 5% suppression:   \", avg_peak(stats_central), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTargeted 5% suppression:    19 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"── Difference in peak time vs. no-suppression ──────────\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n── Difference in peak time vs. no-suppression ──────────\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Random suppression:        \", avg_peak(stats_random)  - avg_peak(stats_normal_5),\n    sprintf(\"(%.1f%%)\\n\", 100 * (avg_peak(stats_random)  - avg_peak(stats_normal_5)) / avg_peak(stats_normal_5)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRandom suppression:         0 (0.0%)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Targeted suppression:      \", avg_peak(stats_central) - avg_peak(stats_normal_5),\n    sprintf(\"(%.1f%%)\\n\", 100 * (avg_peak(stats_central) - avg_peak(stats_normal_5)) / avg_peak(stats_normal_5)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTargeted suppression:       14 (280.0%)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Targeted vs. random:   \", avg_peak(stats_central) - avg_peak(stats_random),\n    sprintf(\"(%.1f%%)\\n\", 100 * (avg_peak(stats_central) - avg_peak(stats_random)) / avg_peak(stats_random)), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTargeted vs. random:    14 (280.0%)\n \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"── Standard deviation (total infected) ──────────────────\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n── Standard deviation (total infected) ──────────────────\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"No suppression:             \", sd(stats_normal_5$total), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNo suppression:              66.91768 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Random suppression:         \", sd(stats_random$total),   \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRandom suppression:          63.46889 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Targeted suppression:       \", sd(stats_central$total),  \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTargeted suppression:        37.18728 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"── Standard deviation (peak time) ────────────────────────\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n── Standard deviation (peak time) ────────────────────────\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"No suppression:             \", sd(stats_normal_5$peak_t), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNo suppression:              1.114103 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Random suppression:         \", sd(stats_random$peak_t),   \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRandom suppression:          1.087968 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Targeted suppression:       \", sd(stats_central$peak_t),  \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTargeted suppression:        5.95387 \n```\n\n\n:::\n:::\n\n\n\n\n\nOn average, randomly suppressing 5% of the population from spreading information results in a similar transmission pattern as no suppression, albeit with a slight reduction (1.5%) in total infections that mostly occurs at the peak. Both the no-suppression and random 5% suppression peak quite quickly, on average, at t = 5. In comparison, targeting the suppression results in a much greater reduction in total infections (34.4% less than no suppression, 33.3% less than random suppression), and the peak is pushed until much later, to t = 19 on average, 14 steps later than either no or random suppression. This indicates that silencing highly connected hub nodes is far more effective at containing the spread of information that randomly silencing the same number of nodes, consistent with the network's hub-dominated structure as described above. \n\nThis suggests that those key nodes such as Epstein, Trump and Dershowitz have structural power over the spread of  information through the network.  \n\n## Comparing Targeted Seeding and Targeted Suppression\n\nWhen finding a targeted seed, we used closeness centrality to identify the 1% of nodes that would maximise information spread when used as seeds. Average over 50 runs, targeting seeding had a negligible effect on total infections when compared to random selection (967 vs. 983), but the peak of infection arrived four time steps earlier (t = 3 vs. t = 7). On the other hand, we also used closeness but in the opposite direction: to identify the 5% of nodes whose silencing would most effectively block the spread. The targeted suppression reduced total infections by 34.4% relative to no intervention and 33.3% relative to random suppression, and it delayed the peak from t = 5 to t = 19.\n\nThe same nodes are the ones that drive both effects: In targeted seeding, closeness identifies the best positioned to _quickly_ push information across the network (Trump, Epstein, Dershowitz etc.), even though it does not change how far that information ultimately reaches. In targeted suppression, the algorithm flags the same actors as the most damaging to silence, because of them being bridges through which information would flow. The hubs that accelerate the diffusion when activated are the same ones that paralyse diffusion when silenced. \n\nWe can understand the symmetry based not only on the findings of this file, but also based on the ones before. The heavily skewed degree distribution and the dominance of a handful high-degree actors that we documented previously help us understand these findings. In our network, where most pathways of information run through only a small set of central nodes, interventions that target these nodes will outperform random strategies. By touching the main central nodes with targeted interventions, we concentrate the effort where the network's structure will notice the impact.\n\nIn the Epstein network, the small set of high centrality actors hold disproportionate power over how information moves through the network. They could spread a narrative very fast if coordinated and block effectively if they stay silent. The behavior of the rest of the network relies heavily on what Trump, Epstein, Dershowitz and other central actors do. This gives insight into how a small number of well-connected actors have a large, structural influence over which information moves through the network. \n\n## A Predictive Model for Seeding and Suppression\n\nRather than relying on a single centrality measure, we train a model to predict each node's time-to-infection from several structural features simultaneously, including degree, closeness, betweeness and page rank. The predictions of that model are then used to select seeds and suppression targets. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2406)\n# Train data\nseeds_train <- sample(seq_len(vcount(epstein)), round(vcount(epstein) * 0.01))\nrealization_train <- sim_sir(epstein, beta = beta_val, mu = mu_val,\n                             seeds = seeds_train)\n\n# Per-node time of infection \nnode_times <- realization_train |>\n  group_by(inf) |>\n  summarise(t = min(t), .groups = \"drop\")\n\n# Centrality predictors\npredictors <- data.frame(\n  inf         = seq_len(vcount(epstein)),\n  degree      = as.numeric(degree(epstein)),\n  closeness   = as.numeric(closeness(epstein)),\n  betweenness = as.numeric(betweenness(epstein)),\n  page_rank   = as.numeric(page_rank(epstein)$vector)\n)\n\n# Merge: only nodes that got infected appear in the training data\ntrain_data <- merge(predictors, node_times, by = \"inf\")\n\n# Training the linear model\nfit <- lm(t ~ degree + closeness + betweenness + page_rank, data = train_data)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = t ~ degree + closeness + betweenness + page_rank, \n    data = train_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-15.069  -3.650  -0.988   1.787  34.539 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  1.941e+01  1.397e+00  13.895  < 2e-16 ***\ndegree      -7.319e-01  1.602e-01  -4.570 5.45e-06 ***\ncloseness   -4.992e+04  5.955e+03  -8.383  < 2e-16 ***\nbetweenness -4.573e-05  4.721e-05  -0.969    0.333    \npage_rank    8.670e+03  2.195e+03   3.950 8.32e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.765 on 1074 degrees of freedom\nMultiple R-squared:  0.1599,\tAdjusted R-squared:  0.1567 \nF-statistic: 51.09 on 4 and 1074 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predict time-to-infection for ALL nodes including never-infected ones\npredictors$predicted_t <- predict(fit, newdata = predictors)\n# Smallest predicted t = nodes that should get infected earliest = strongest spreaders\nhead(predictors[order(predictors$predicted_t), ], 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    inf degree    closeness betweenness   page_rank predicted_t\n21   21    269 0.0003175611   169868.02 0.022197706  -8.6332338\n27   27    142 0.0002890173    53641.95 0.011418397  -2.4022163\n30   30     85 0.0002871088    25352.79 0.006577730  -1.2652476\n338 338     83 0.0002912904    53979.69 0.006587884  -1.2314239\n18   18     78 0.0002718130    13011.55 0.005884970  -0.8204638\n397 397     61 0.0002840909    26849.66 0.004660540  -0.2402436\n50   50     88 0.0002921414    45976.19 0.007169605   0.4763155\n31   31     66 0.0002721829    12563.09 0.005050353   0.7278842\n152 152     84 0.0002746498    19921.87 0.006648734   0.9525279\n47   47    112 0.0002775465    72751.15 0.009389487   1.6618658\n```\n\n\n:::\n\n```{.r .cell-code}\n# Scenario (c): seeds chosen by smallest predicted t (maximise spread)\nset.seed(2406)\nn_seeds <- round(vcount(epstein) * 0.01)\nseeds_model <- predictors[order(predictors$predicted_t), \"inf\"][seq_len(n_seeds)]\n\nruns_seeds_model <- map_dfr(seq_len(N_RUNS), function(i){\n  sim_sir(epstein, beta_val, mu_val, seeds_model) |>\n    group_by(t) |> summarise(ninf = n(), .groups = \"drop\") |> mutate(run = i)\n})\ncurve_seeds_model <- runs_seeds_model |> group_by(t) |> summarise(ninf = mean(ninf), .groups = \"drop\")\n\n# Scenario (d): silence 5% with smallest predicted t, then 1% random seeds\nn_vax <- round(vcount(epstein) * 0.05)\nvax_model <- predictors[order(predictors$predicted_t), \"inf\"][seq_len(n_vax)]\n\nn_seeds_vax <- round(vcount(epstein) * 0.01)\nruns_vax_model <- avg_sim(epstein, beta_val, mu_val, n_seeds_vax, no_spread = vax_model)\ncurve_vax_model <- runs_vax_model |> group_by(t) |> summarise(ninf = mean(ninf), .groups = \"drop\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_line(data = curve_normal_5,    aes(x = t, y = ninf, col = \"(a) Random seeds\")) +\n  geom_line(data = curve_random,      aes(x = t, y = ninf, col = \"(b) Random 5% suppression\")) +\n  geom_line(data = curve_seeds_model, aes(x = t, y = ninf, col = \"(c) Model-selected seeds\")) +\n  geom_line(data = curve_vax_model,   aes(x = t, y = ninf, col = \"(d) Model-selected suppression\")) +\n  labs(y = \"Mean new infections\", x = \"Time\",\n       title = paste0(\"Model-based vs. random seeding and suppression\\n(mean over \", N_RUNS, \" runs)\"),\n       color = \"Scenario\")\n```\n\n::: {.cell-output-display}\n![](03-diffusion-modelling_files/figure-html/four-scenario-comparison-1.png){width=672}\n:::\n\n```{.r .cell-code}\nstats_seeds_model <- per_run_stats(runs_seeds_model)\nstats_vax_model   <- per_run_stats(runs_vax_model)\n\ncat(\"── Average total infected ──────────────────────────\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n── Average total infected ──────────────────────────\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"(a) Random seeds:                 \", avg_total(stats_normal_5),    \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(a) Random seeds:                  1200 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"(b) Random 5% suppression:        \", avg_total(stats_random),      \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(b) Random 5% suppression:         1182 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"(c) Model-selected seeds:         \", avg_total(stats_seeds_model), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(c) Model-selected seeds:          1196 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"(d) Model-selected suppression:   \", avg_total(stats_vax_model),   \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(d) Model-selected suppression:    798 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"── Average peak time ───────────────────────────────\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n── Average peak time ───────────────────────────────\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"(a) Random seeds:                 \", avg_peak(stats_normal_5),    \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(a) Random seeds:                  5 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"(b) Random 5% suppression:        \", avg_peak(stats_random),      \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(b) Random 5% suppression:         5 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"(c) Model-selected seeds:         \", avg_peak(stats_seeds_model), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(c) Model-selected seeds:          3 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"(d) Model-selected suppression:   \", avg_peak(stats_vax_model),   \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(d) Model-selected suppression:    21 \n```\n\n\n:::\n:::\n\n\n\n\n\nWe trained a linear model to predict each node's time-to-infection using degree, closeness, betweeness and page rank, from one random-seed SIR realisation at β = 0.1. The model achieves an R2 of 0.16, where closeness is the dominant predictor (t = -8.4) and degree follows (t = -4.6). Both values are negative, confirming that the more central the nodes, the earlier they get infected. Betweeness is not significant in this model. Although as we could see from the low R2 value the model explains only a modest fraction, what matters is that it produces a useful ranking of nodes by influence, and that is what we need to select seeds and silencing targets. \n\nWe can take some conclusions from the four-scenario comparison. Model-selected seeds (c) infect almost the same number as people as random seeds, but reach peak infection two time steps earlier. With β = 0.1 the network is above its epidemic threshold, so eventually the infection saturates the giant component regardless of where it starts. On the contrary, model-selected silencing (d) is more effective: it cuts total infections by 32.5% relative to random silencing, and shifts the peak from t= 5 to t = 21. By silencing the right 5% of nodes, it effectively fragments the network's diffusion structure before the outbreak can develop. \n\nThe difference between (c) and (d) shows us that targeted promotion has diminishing returns once transmission probability is high. The spread happens fast whether you start from either the perfect node or a random one. But targeted suppression remains highly effective even at high β, because silencing well-chosen nodes physically disconnects parts of the network and limits the maximum reach of any outbreak.\n\nThe linear model is dominated by closeness and in such a hub-centered network closeness alone already identifies most of the structurally critical nodes. But the model adds value mainly by formalising and combining centrality signals rather than uncovering new ones. Because of the structure of our network, closeness is such a strong value that other structural signals are more marginal. \n",
    "supporting": [
      "03-diffusion-modelling_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}