{
  "hash": "525c2d92b8dcd07e77f3d07de061daba",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Link Prediction\"\nformat: \n  html:\n    embed-resources: true\neditor: visual\n---\n\n\n\n\n\n## Introduction\n\nThis page frames link prediction as a binary classification problem on the Epstein network: can proximity-based heuristics distinguish real relationships from non-existent ones? We train a logistic regression classifier on similarity metrics computed from held-out edges, evaluate it with cross-validation, and identify which heuristic is most predictive.\n\nThe network studied in this file is an extension of the previous one (Network Exploration), now constructed from the top 1700 nodes, rather than the top 500. Again, it solely examines the giant component. Following the final robustness check in the previous analysis, this file will work on the filtered network in which all \"unknown\" composite nodes have been removed. As discussed there, these nodes represent multiple distinct individuals collapsed into a single label by the data extraction pipeline, and they distort centrality and structural measures. The graph is also left unweighted, using neighbourhood overlap and degree to predict links. \n\n\n## Set-Up\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsource(\"data-prep.R\")\nlibrary(boot)\nlibrary(caret)\n```\n:::\n\n\n\n\n\n## Network Construction\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Build edge list from actor-target pairs\nedgelist <- raw[, c(\"actor\", \"target\")]\n\n# Count how often each entity appears\nentity_freq <- table(c(edgelist$actor, edgelist$target))\ntop1700       <- names(sort(entity_freq, decreasing = TRUE))[1:1700]\n\n# Keep edges where both endpoints are in the top 1700\nedgelist <- edgelist[edgelist$actor %in% top1700 & edgelist$target %in% top1700, ]\n\n# Build and simplify\nepstein <- graph.data.frame(edgelist, directed = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: `graph.data.frame()` was deprecated in igraph 2.0.0.\nℹ Please use `graph_from_data_frame()` instead.\n```\n\n\n:::\n\n```{.r .cell-code}\nepstein <- igraph::simplify(epstein)\nepstein\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIGRAPH 237c653 UN-- 1639 6280 -- \n+ attr: name (v/c)\n+ edges from 237c653 (vertex names):\n [1] Jeffrey Epstein--Palm Beach Police Department\n [2] Jeffrey Epstein--Larry Visoski               \n [3] Jeffrey Epstein--Prince Andrew               \n [4] Jeffrey Epstein--Michael Reiter              \n [5] Jeffrey Epstein--grand jury                  \n [6] Jeffrey Epstein--Guy Fronstin                \n [7] Jeffrey Epstein--Alex Acosta                 \n [8] Jeffrey Epstein--Ric Bradshaw                \n+ ... omitted several edges\n```\n\n\n:::\n\n```{.r .cell-code}\n# Filter out \"unknown\" composite nodes \nunknown_nodes <- V(epstein)$name[grepl(\"unknown\", V(epstein)$name, ignore.case = TRUE)]\ncat(\"Removing\", length(unknown_nodes), \"unknown composite nodes\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRemoving 107 unknown composite nodes\n```\n\n\n:::\n\n```{.r .cell-code}\nepstein <- delete_vertices(epstein, unknown_nodes)\n\n# Using giant component\nepstein <- decompose(epstein)[[which.max(sapply(decompose(epstein), vcount))]]\n\n# Node and Edges Count\ncat(\"Nodes:\", vcount(epstein), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNodes: 1491 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Edges:\", ecount(epstein), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEdges: 5124 \n```\n\n\n:::\n:::\n\n\n\n\n\n## Link Removal: held out edges\n\nTo train and test a prediction model, 20% of the 5124 links in the network will be removed as the positive class, and an equal number of edges between well-connected nodes that do not exist in the network will be sampled as the negative class.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnlinks <- floor(0.2 * ecount(epstein)) # Deleting 20% of nodes\n\n# Sampling 5000 random edge indices from the full network\nset.seed(111)\nindexes_deleted <- sample(1:ecount(epstein), nlinks)\n\n# The \"observed\" graph with those edges removed\nepstein_prime <- delete_edges(epstein, indexes_deleted)\n\n# Positive Class - Deleted Edges\ndeleted_endpoints <- get.edges(epstein, indexes_deleted)\ntrue_edges <- data.frame(\n  X1  = deleted_endpoints[, 1],\n  X2  = deleted_endpoints[, 2]\n)\n\n# Negative class: non-existent links from well-connected nodes\nfalse_edges    <- data.frame()\nmost_connected <- which(degree(epstein) > 10)\n\nset.seed(111)\nwhile (nrow(false_edges) < nlinks) {\n  node_pair <- sample(most_connected, 2)\n  node1     <- node_pair[1]\n  node2     <- node_pair[2]\n  \n  if (get.edge.ids(epstein, c(node1, node2)) == 0) {\n    false_edges <- rbind(false_edges, data.frame(X1 = node1, X2 = node2))\n  }\n}\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: `get.edge.ids()` was deprecated in igraph 2.1.0.\nℹ Please use `get_edge_ids()` instead.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Assign obs labels and bind\ntrue_edges  <- data.frame(true_edges,  obs = 1)\nfalse_edges <- data.frame(false_edges, obs = 0)\n\ntotal_edges           <- rbind(true_edges, false_edges)\ncolnames(total_edges) <- c(\"id1\", \"id2\", \"obs\")\n\nhead(total_edges)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id1  id2 obs\n1  19   38   1\n2   1  350   1\n3 176  179   1\n4   4   34   1\n5  63  731   1\n6 366 1484   1\n```\n\n\n:::\n:::\n\n\n\n\n\n## Proximity Metrics\n\nGenerate a number of proximity/similarty metrics heuristics for each link in the positive and negative class\n\nFor every real or fake edge in `total_edges`, three proximity metrics are computed on the network with the positive class edges removed (`epstein_prime`). These metrics are Jaccard, Adamic-Adar and Preferential Attachment. They measure the following:\n\n-   **Jaccard** (`sim_jacc`): the fraction of neighbours that two nodes share, where 1 indicates identical neighbours and 0 is no overlap at all.\n\n-   **Adamic-Adar** (`sim_aa`): counts common neighbours like Jaccard, but weights each shared neighbour by the inverse log of their degree. This metric captures the logic that a shared neighbour who only has a few connections indicates a stronger link.\n\n-   **Preferential Attachment** (`sim_pref`): the product of the two nodes' degrees, capturing the likelihood of two nodes being connected based on their overall popularity. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn1 <- neighborhood(epstein_prime, order = 1, nodes = total_edges$id1)\nn2 <- neighborhood(epstein_prime, order = 1, nodes = total_edges$id2)\n\ntotal_edges$sim_jacc <- 0\ntotal_edges$sim_aa   <- 0\ntotal_edges$sim_pref <- 0\n\nfor (i in 1:nrow(total_edges)) {\n  nei1   <- n1[[i]]\n  nei2   <- n2[[i]]\n  common <- intersect(nei1, nei2)\n\n  # Jaccard: fraction of shared neighbours\n  all_nei <- union(nei1, nei2)\n  if (length(all_nei) > 0) {\n    total_edges$sim_jacc[i] <- length(common) / length(all_nei)\n  }\n\n  # Adamic-Adar: shared neighbours weighted by inverse log degree\n  if (length(common) > 0) {\n    deg_common <- degree(epstein_prime, common)\n    deg_common <- deg_common[deg_common > 1]\n    total_edges$sim_aa[i] <- sum(1 / log(deg_common))\n  }\n\n  # Preferential attachment: product of degrees\n  total_edges$sim_pref[i] <- degree(epstein_prime, total_edges$id1[i]) *\n                               degree(epstein_prime, total_edges$id2[i])\n}\n\nhead(total_edges)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id1  id2 obs    sim_jacc    sim_aa sim_pref\n1  19   38   1 0.035087719 0.8804312      110\n2   1  350   1 0.005565863 1.7180964     1611\n3 176  179   1 0.066666667 0.7213475       40\n4   4   34   1 0.078431373 0.8616289      700\n5  63  731   1 0.052631579 0.7058427      217\n6 366 1484   1 0.000000000 0.0000000        3\n```\n\n\n:::\n:::\n\n\n\n\n\n## Classifier and Cross-Validation\n\nWe frame link prediction as a binary classification problem (there either exists a link or not) and fit a logistic regression model on the three heuristics computed above. A 10-fold cross-validation is then run to check the model generalises and is not overfitting to a single train/test split\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Train and test split\nset.seed(111)\ntrain_idx <- sample(1:nrow(total_edges), 0.7 * nrow(total_edges))\ntotal_edges_train <- total_edges[train_idx, ]\ntotal_edges_test  <- total_edges[-train_idx, ]\n\n# Logistic regression model\nglm_link <- glm(obs ~ sim_jacc + sim_aa + sim_pref,\n                data   = total_edges_train,\n                family = binomial(link = \"logit\"))\n\nsummary(glm_link)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = obs ~ sim_jacc + sim_aa + sim_pref, family = binomial(link = \"logit\"), \n    data = total_edges_train)\n\nCoefficients:\n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -3.665e-01  7.062e-02  -5.189 2.11e-07 ***\nsim_jacc     8.394e-01  1.544e+00   0.544 0.586693    \nsim_aa       1.194e+00  1.690e-01   7.063 1.63e-12 ***\nsim_pref    -2.444e-04  7.062e-05  -3.461 0.000538 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1986.5  on 1432  degrees of freedom\nResidual deviance: 1853.7  on 1429  degrees of freedom\nAIC: 1861.7\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predict on the test set\nglm_prediction <- predict.glm(glm_link,\n                              newdata = total_edges_test,\n                              type    = \"response\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(111)\nglm_full <- glm(obs ~ sim_jacc + sim_aa + sim_pref,\n                data   = total_edges,\n                family = binomial(link = \"logit\"))\n\ncv_result <- cv.glm(total_edges, glm_full, K = 10)\ncat(\"10-fold CV error estimate:\", round(cv_result$delta[1], 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n10-fold CV error estimate: 0.2274 \n```\n\n\n:::\n:::\n\n\n\n\n\nThe 10-fold cross-validation error is 0.227. A model which just guesses gives an error of 0.25, so while the model has learnt slightly from the data it is not too far from just randomly guessing.\n\n## Model Evaluation\n\nWe evaluate the model with a confusion matrix using a 0.5 probability threshold.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Apply threshold\npred <- ifelse(glm_prediction > 0.5, 1, 0)\n\n# Confusion matrix\nconf_mat <- confusionMatrix(factor(pred, levels = c(0, 1)),\n                            factor(total_edges_test$obs, levels = c(0, 1)),\n                            positive = \"1\")\nconf_mat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nConfusion Matrix and Statistics\n\n          Reference\nPrediction   0   1\n         0 241 157\n         1  70 147\n                                          \n               Accuracy : 0.6309          \n                 95% CI : (0.5914, 0.6691)\n    No Information Rate : 0.5057          \n    P-Value [Acc > NIR] : 2.691e-10       \n                                          \n                  Kappa : 0.2593          \n                                          \n Mcnemar's Test P-Value : 1.143e-08       \n                                          \n            Sensitivity : 0.4836          \n            Specificity : 0.7749          \n         Pos Pred Value : 0.6774          \n         Neg Pred Value : 0.6055          \n             Prevalence : 0.4943          \n         Detection Rate : 0.2390          \n   Detection Prevalence : 0.3528          \n      Balanced Accuracy : 0.6292          \n                                          \n       'Positive' Class : 1               \n                                          \n```\n\n\n:::\n:::\n\n\n\n\n\nThe accuracy of the model is 0.631, indicating that the model correctly predicts the presence of a link around 63% of the time. The sensitivity (0.484) is  is well below the specificity (0.775), illustrating the model correctly identifies the absence of a link significantly better than its presence. The Kappa value is 0.259, indicating that the model is better than randomly guessing but fails to predict a significant amount of the true links.\n\nThe `summary(glm_link)` output above shows the coefficient and significance (z-statistic, p-value) of each heuristic. The heuristic with the largest absolute z-statistic is the most important predictor. From the below table, it can be seen that Adamic-Adar (z = 7.06, p < 0.001) and Preferential Attachment (z = -3.46, p < 0.001) are statistically significant predictors, whereas Jaccard is not (z = 0.54, p = 0.59). Of the three, Adamic-Adar has the largest absolute z-value and therefore is the most important, indicating that what best predicts the presence of a link is the shared neighbours of two nodes, weighted by the inverse log of the degree (where a connection with a less popular neighbour signifies a stronger link).\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract z-statistics from the fitted model\ncoefs <- summary(glm_link)$coefficients\ncoefs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 Estimate   Std. Error    z value     Pr(>|z|)\n(Intercept) -0.3664572860 7.062030e-02 -5.1891208 2.112892e-07\nsim_jacc     0.8393522888 1.543964e+00  0.5436347 5.866929e-01\nsim_aa       1.1935757150 1.689854e-01  7.0631873 1.627261e-12\nsim_pref    -0.0002444206 7.061908e-05 -3.4611134 5.379462e-04\n```\n\n\n:::\n:::\n\n\n\n\n\n## Possible Improvements\n\n*Using the type of relationship*: The original dataset includes a description of the relationship between the different actors of the network. For the purpose of this work, we collapsed all of these into a single undirected edge and discarded the actual nature of these interactions/ relationships (sending an email, signing a deposition, travelling together, being accused by, prosecuting, etc.). To make more accurate predictions, we could incorporate the relationship type as an edge feature, or train separate models per relationship type, giving the predictor much richer information than a binary \"connected or not\".\n\n*Using weighted edges*: We are treating every pair of entities that ever appeared together in a document as connected, regardless of how often. If we incorporated the number of times two entities interact, we could distinguish between strong and incidental relationships and provide the heuristics with more precise input.\n\n*Add node-level features*: The current model only uses proximity metrics to predict whether a link exists between two nodes. Adding additional node-level features such as degree, centrality and community membership would give the model richer detail and potentially improve the accuracy of predictions.\n",
    "supporting": [
      "02-link-prediction_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}